name: Build & Pack

on: [push]


jobs:

  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: msbuild Transitions\Transitions.csproj -t:Restore,Build -p:Configuration=Release
      # -t:Pack   -p:IncludeSymbols=true

  deploy:
    if: github.ref == 'refs/heads/master'