name: Build & Pack

on: [push]


jobs:

  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build
      run: msbuild -t:Restore,Build,Pack -p:Configuration=Release,IncludeSymbols=true

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
