name: Build & Pack

on: [push]


jobs:

  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build
      run: msbuild Transitions\Transitions.csproj -t:Restore,Build -p:Configuration=Release

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: msbuild Transitions\Transitions.csproj -t:Pack -p:Configuration=Release,IncludeSymbols=true
    
